"""Dữ liệu test artwork - Tiếng Việt."""

COLUMNS_VI = [
    "STT",
    "Danh mục",
    "Loại Artwork",
    "Phong cách / Biến thể",
    "Mô tả",
    "Xuất xứ / Văn hóa",
    "Độ phức tạp màu",
    "Mức độ chi tiết",
    "Trong suốt (Alpha)",
    "Định dạng file",
    "Kỹ thuật in",
    "Chất lượng in dự kiến",
    "Thách thức AI Try-on",
    "Trọng tâm kiểm thử",
    "Prompt mẫu (AI Gen)",
    "Độ ưu tiên",
    "[Result]- Tạo Artwork",
    "Đánh giá kết quả Tạo Artwork",
    "Link data kết quả Tạo Artwork",
    "[Result] Try-on Model AI (Nam)",
    "Đánh giá Model AI (Nam)",
    "Link data kết quả Tryon (Nam)",
    "[Result] Try-on Model AI (Nữ)",
    "Đánh giá Model AI (Nữ)",
    "Link data kết quả Tryon (Nữ)",
    "Link Ảnh Sample"
]
COL_WIDTHS = [5, 30, 22, 24, 40, 18, 16, 14, 16, 18, 22, 20, 18, 40, 40, 12, 16, 28, 28, 16, 28, 28, 16, 28, 28, 25]

ARTWORK_DATA_VI = {
    "🎨 NGHỆ THUẬT TRUYỀN THỐNG": [
        ("Tranh sơn dầu", "Trường phái Ấn tượng", "Nét cọ mềm mại, tập trung ánh sáng, màu hòa quyện", "Châu Âu (Pháp)", "Cao", "Phức tạp", "Không", "JPG/PNG", "DTG, Thăng hoa", "Tốt", "Trung bình", "Độ chính xác tái tạo màu, kết cấu nét cọ trên vải", "Tranh sơn dầu ấn tượng hoa hướng dương lúc hoàng hôn", "P1", "Chi tiết kết cấu có thể mất ở bản in nhỏ"),
        ("Tranh sơn dầu", "Siêu thực", "Tranh giống ảnh thật với chi tiết cực cao", "Toàn cầu", "Rất cao", "Cực cao", "Không", "JPG/PNG", "DTG", "Xuất sắc", "Thấp", "Xử lý độ phân giải cực cao, độ sắc nét cạnh trên vải", "Tranh sơn dầu siêu thực giọt nước trên kính", "P1", "Yêu cầu ảnh gốc cao (300+ DPI)"),
        ("Tranh màu nước", "Ướt trên ướt", "Lớp rửa trong suốt, cạnh mềm, loang tự nhiên", "Toàn cầu", "Trung bình", "Vừa phải", "Có", "PNG", "DTG, Thăng hoa", "Tốt", "Trung bình", "Bảo toàn độ trong suốt, gradient mềm trên vải", "Tranh màu nước hoa anh đào kỹ thuật ướt", "P1", "Xử lý kênh alpha rất quan trọng"),
        ("Tranh màu nước", "Minh họa thực vật", "Vẽ cây chính xác với kỹ thuật màu nước", "Châu Âu (Anh)", "Trung bình", "Phức tạp", "Có", "PNG", "DTG", "Xuất sắc", "Thấp", "Bảo toàn đường nét mảnh + hòa trộn màu nước trong suốt", "Minh họa thực vật màu nước loài phong lan", "P2", "Xóa nền trắng là quan trọng"),
        ("Tranh acrylic", "Biểu hiện Trừu tượng", "Màu đậm, kết cấu dày, bố cục năng động", "Mỹ", "Rất cao", "Phức tạp", "Không", "JPG/PNG", "DTG, Thăng hoa", "Tốt", "Thấp", "Tái tạo độ rực rỡ màu, kết cấu vẽ", "Tranh acrylic trừu tượng với vệt sơn đậm", "P1", "Màu rực có thể lệch khi in CMYK"),
        ("Tranh than chì", "Chân dung", "Đơn sắc, tương phản cao, chuyển sắc tinh tế", "Toàn cầu", "Thấp", "Phức tạp", "Không", "JPG/PNG", "DTG, In lụa", "Xuất sắc", "Thấp", "Độ chính xác thang xám, bảo toàn chi tiết mảnh", "Tranh than chì chân dung người già", "P2", "Hiệu quả trên cả áo sáng và tối"),
        ("Tranh mực", "Nét vẽ (Line Art)", "Đường nét sạch, ít bóng đổ, phong cách bút mực", "Toàn cầu", "Thấp", "Đơn giản", "Có", "SVG/PNG", "In lụa, DTG", "Xuất sắc", "Không", "Độ sắc nét đường, khả năng co giãn, xử lý trong suốt", "Tranh mực nét vẽ phong cảnh núi", "P0", "Loại artwork cơ bản nhất — test nền tảng"),
        ("Phác thảo bút chì", "Phác thảo thực tế", "Chì trên giấy, bóng đổ mềm, dải tông rộng", "Toàn cầu", "Thấp", "Vừa phải", "Không", "JPG/PNG", "DTG", "Tốt", "Thấp", "Chuyển sắc tông tinh tế, kết cấu giấy", "Phác thảo chi tiết bút chì con mèo", "P2", "Tương phản thấp có thể mất trên áo màu"),
        ("Tranh phấn màu", "Phấn mềm", "Kết cấu mịn, màu rực mềm, hòa trộn", "Châu Âu", "Cao", "Vừa phải", "Không", "JPG/PNG", "DTG, Thăng hoa", "Tốt", "Trung bình", "Tái tạo gradient mềm, độ chính xác màu phấn", "Phong cảnh phấn mềm cánh đồng oải hương", "P2", "Màu nhạt cần profile màu chính xác"),
        ("Tranh khắc", "Khắc gỗ / Lino", "Hình dạng đồ họa đậm, tương phản cao, kết cấu chạm khắc", "Nhật/Châu Âu", "Thấp", "Vừa phải", "Không", "SVG/PNG", "In lụa", "Xuất sắc", "Không", "Vùng màu đặc sạch, cạnh sắc nét", "Tranh khắc gỗ con sói trong rừng", "P1", "Lý tưởng cho in lụa"),
        ("Tranh khắc", "In đá (Lithography)", "Chuyển sắc tông, in màu nhiều lớp", "Châu Âu", "Trung bình", "Phức tạp", "Không", "JPG/PNG", "DTG", "Tốt", "Thấp", "Tái tạo đa tông, độ chính xác chồng lớp", "Tranh in đá thực vật cổ điển", "P2", "Thẩm mỹ in truyền thống"),
        ("Nghệ thuật khảm", "Byzantine / Gạch men", "Mẫu pixel hóa từ mảnh nhỏ, hình học", "Trung Đông/Địa Trung Hải", "Cao", "Phức tạp", "Không", "JPG/PNG", "DTG, Thăng hoa", "Tốt", "Thấp", "Độ rõ mẫu, phân đoạn màu trên vải", "Khảm Byzantine thiên thần vàng", "P3", "Test mức zoom quan trọng"),
    ],

    "💻 NGHỆ THUẬT SỐ": [
        ("Đồ họa vector", "Thiết kế phẳng (Flat)", "Hình hình học sạch, màu phẳng đặc, không gradient", "Toàn cầu", "Trung bình", "Đơn giản", "Có", "SVG/AI/PNG", "In lụa, DTG, HTV", "Xuất sắc", "Không", "Test co giãn, độ chính xác màu phẳng, trong suốt", "Minh họa vector phẳng cảnh thành phố", "P0", "Định dạng chính cho POD — phải hoàn hảo"),
        ("Đồ họa vector", "Isometric", "Góc nhìn 3D giả với phối cảnh đẳng cự", "Toàn cầu", "Trung bình", "Vừa phải", "Có", "SVG/PNG", "DTG", "Xuất sắc", "Thấp", "Độ chính xác phối cảnh, đường thẳng trên đường cong cơ thể", "Minh họa isometric quán cà phê", "P2", "Đường thẳng có thể biến dạng trên body"),
        ("Vẽ kỹ thuật số", "Bán thực tế", "Nét cọ số hòa trộn, độ thực vừa phải", "Toàn cầu", "Cao", "Phức tạp", "Không", "PNG/PSD", "DTG, Thăng hoa", "Tốt", "Trung bình", "Kết cấu cọ trên vải, độ sâu màu", "Tranh số bán thực tế nhân vật chiến binh", "P1", "Test nghệ thuật số tiêu chuẩn"),
        ("Vẽ kỹ thuật số", "Concept Art", "Thiết kế nhân vật/môi trường cho game/phim", "Toàn cầu", "Cao", "Phức tạp", "Có", "PNG/PSD", "DTG", "Tốt", "Trung bình", "Cắt bố cục phức tạp, trong suốt nền", "Concept art tàu vũ trụ sci-fi trong tinh vân", "P1", "Thường có nền trong suốt"),
        ("Pixel Art", "Retro 8-bit", "Pixel thô, bảng màu giới hạn, game cổ điển", "Nhật/Mỹ", "Thấp", "Đơn giản", "Có", "PNG/GIF", "In lụa, DTG", "Xuất sắc", "Không", "Pixel sắc nét (không anti-alias), chất lượng phóng to", "Pixel art 8-bit nhân vật game retro", "P1", "KHÔNG được áp dụng làm mịn/nội suy"),
        ("Pixel Art", "Pixel độ phân giải cao", "Pixel art hiện đại canvas lớn, nhiều màu hơn", "Toàn cầu", "Trung bình", "Vừa phải", "Có", "PNG", "DTG", "Xuất sắc", "Thấp", "Duy trì lưới pixel ở kích thước in", "Pixel art phong cảnh hi-res với lớp parallax", "P2", "Tỷ lệ phóng phải là bội số nguyên"),
        ("Render 3D", "Render ảnh thực", "Cảnh 3D ray-traced với ánh sáng, bóng đổ", "Toàn cầu", "Rất cao", "Cực cao", "Không", "JPG/PNG", "DTG, Thăng hoa", "Xuất sắc", "Thấp", "Render bóng, phản quang trên vải", "Render 3D thực tế robot chrome", "P1", "File lớn — test hiệu năng"),
        ("Render 3D", "Low Poly", "3D đơn giản hóa với mặt đa giác nhìn thấy", "Toàn cầu", "Trung bình", "Vừa phải", "Có", "PNG", "DTG, In lụa", "Xuất sắc", "Không", "Sắc nét cạnh đa giác, gradient trong các mặt", "Chân dung đầu thú low poly 3D", "P1", "Phong cách POD phổ biến"),
        ("Collage kỹ thuật số", "Chỉnh sửa ảnh ghép", "Ghép nhiều ảnh với hiệu ứng số", "Toàn cầu", "Rất cao", "Cực cao", "Có", "PNG/PSD", "DTG", "Tốt", "Trung bình", "Hòa trộn lớp trên vải, phát hiện artifact cạnh", "Collage siêu thực đảo bay lơ lửng", "P2", "Kênh alpha phức tạp"),
        ("Khung Motion Graphics", "Poster động", "Khung đơn từ animation, bố cục năng động", "Toàn cầu", "Cao", "Phức tạp", "Có", "PNG", "DTG", "Tốt", "Trung bình", "Độ rõ phần tử động trong bản in tĩnh", "Poster động với hạt particle chảy", "P3", "Có thể mất bối cảnh chuyển động"),
        ("Nghệ thuật sinh tạo", "Thuật toán / Fractal", "Mẫu tạo bằng toán học, chi tiết vô hạn", "Toàn cầu", "Rất cao", "Cực cao", "Không", "PNG/JPG", "Thăng hoa", "Tốt", "Thấp", "Độ phân giải chi tiết fractal ở kích thước in", "Fractal Mandelbrot gradient cầu vồng", "P2", "Đẹp ở độ phân giải cao, mapping màu phức tạp"),
    ],

    "🤖 PHONG CÁCH AI TẠO SINH": [
        ("AI Thực tế", "Chân dung giống ảnh thật", "Chân dung người AI tạo, gần chất lượng ảnh thật", "AI (Midjourney/SD)", "Cao", "Cực cao", "Không", "PNG/JPG", "DTG", "Tốt", "Cao", "Phát hiện artifact AI khi in, khuôn mặt in vs model try-on", "Chân dung thực tế phụ nữ với hoa trong tóc, ánh sáng dramatic", "P0", "QUAN TRỌNG: AI Try-on có thể nhầm mặt in với model"),
        ("AI Fantasy", "Cảnh Fantasy hoành tráng", "Phong cảnh fantasy kịch tính, nhân vật nghệ thuật", "AI (Midjourney/SD)", "Rất cao", "Cực cao", "Không", "PNG", "DTG, Thăng hoa", "Tốt", "Thấp", "Độ rực rỡ màu, bảo toàn chi tiết ở scale áo", "Rồng fantasy bay trên núi sương mù", "P1", "Chi tiết cao có thể nén kém"),
        ("AI Anime", "Anime / Manga", "Phong cách hoạt hình Nhật với AI tạo", "AI (Midjourney --niji)", "Cao", "Phức tạp", "Có", "PNG", "DTG", "Xuất sắc", "Trung bình", "Chất lượng nét anime, cel-shading trên vải", "Samurai cyber phong cách anime với katana neon", "P0", "Rất phổ biến cho thị trường POD"),
        ("AI Trừu tượng", "Nghệ thuật chất lỏng", "Mẫu trừu tượng chảy do AI tạo", "AI (Midjourney/SD)", "Rất cao", "Phức tạp", "Không", "PNG/JPG", "DTG, Thăng hoa", "Tốt", "Thấp", "Hòa trộn màu mượt, cạnh liền mạch cho allover", "Nghệ thuật chất lỏng trừu tượng vàng pha xanh ngọc", "P1", "Test ghép liền mạch cho in toàn thân"),
        ("AI Chibi", "Kawaii / Chibi", "Nhân vật dễ thương, đầu to quá cỡ", "AI (Midjourney --niji)", "Trung bình", "Vừa phải", "Có", "PNG", "DTG, In lụa", "Xuất sắc", "Thấp", "Bảo toàn độ dễ thương, cắt alpha sạch", "Mèo chibi kawaii phi hành gia với nền ngôi sao", "P1", "Thể loại phổ biến cho áo casual"),
        ("AI Typography", "Text 3D / Chữ nghệ thuật", "Artwork typography do AI tạo", "AI (Midjourney/SD)", "Trung bình", "Vừa phải", "Có", "PNG", "DTG, In lụa", "Tốt", "Không", "Độ đọc được của text, hiệu ứng 3D trên vải phẳng", "Text chrome 3D 'DREAM BIG' với ngọn lửa", "P1", "Phải kiểm tra độ đọc được của chữ"),
        ("AI Siêu thực", "Dreamcore / Chủ nghĩa siêu thực", "Bố cục giấc mơ siêu thực", "AI (Midjourney/SD)", "Cao", "Cực cao", "Không", "PNG/JPG", "DTG", "Tốt", "Trung bình", "Độ rõ phần tử siêu thực, nhận dạng đối tượng trên áo", "Cầu thang siêu thực dẫn lên mây với đồng hồ bay", "P2", "Thú vị nhưng thị trường ngách"),
        ("AI Retro", "Retrowave / Synthwave", "Thẩm mỹ neon thập niên 80, retro-futuristic", "AI (Midjourney/SD)", "Cao", "Vừa phải", "Không", "PNG", "DTG, Thăng hoa", "Tốt", "Thấp", "Tái tạo hiệu ứng neon trên vải, banding gradient", "Hoàng hôn synthwave với cây cọ và DeLorean", "P1", "Bán tốt POD — test gradient quan trọng"),
        ("AI Sticker", "Sticker kiểu dán", "Sticker có viền trắng, nhìn bóng loáng", "AI (Midjourney/SD)", "Trung bình", "Đơn giản", "Có", "PNG", "DTG, HTV", "Xuất sắc", "Không", "Sắc nét viền, ảo giác sticker trên vải", "Sticker dễ thương Corgi với viền trắng dày", "P0", "Format rất phổ biến — test viền trắng"),
        ("AI Màu nước", "Mô phỏng màu nước AI", "Hiệu ứng màu nước do AI tạo", "AI (Midjourney/SD)", "Trung bình", "Phức tạp", "Có", "PNG", "DTG", "Tốt", "Trung bình", "Hiệu ứng loang màu nước, cạnh trong suốt", "Tranh màu nước AI quán café Paris trong mưa", "P2", "So sánh với scan màu nước thật"),
        ("AI Truyện tranh", "Comic / Tiểu thuyết đồ họa", "Phong cách comic AI với halftone, nét đậm", "AI (Midjourney/SD)", "Cao", "Phức tạp", "Không", "PNG", "DTG, In lụa", "Xuất sắc", "Thấp", "Mẫu halftone, render bong bóng hội thoại", "Siêu anh hùng comic trong tư thế hành động", "P2", "Halftone có thể gây hiện tượng moiré"),
    ],

    "🌍 NGHỆ THUẬT VĂN HÓA / VÙNG MIỀN": [
        ("Ukiyo-e Nhật Bản", "Tranh khắc gỗ", "Phong cách Edo, màu phẳng, đường viền đậm, thiên nhiên/nhân vật", "Nhật Bản", "Trung bình", "Phức tạp", "Không", "JPG/PNG", "DTG, In lụa", "Xuất sắc", "Thấp", "Bảng màu truyền thống, kết cấu vân gỗ", "Sóng lớn phong cách Ukiyo-e với twist hiện đại", "P1", "Test nghệ thuật cổ điển trên áo"),
        ("Thủy mặc Trung Quốc", "Sumi-e / Shui-mo", "Tranh cọ tối giản, gradient mực, zen", "Trung Quốc", "Thấp", "Vừa phải", "Có", "PNG", "DTG", "Tốt", "Trung bình", "Trong suốt mực, nét cọ tinh tế trên vải", "Tranh thủy mặc tre trong sương", "P1", "Tông nhạt có thể mất trên áo màu"),
        ("Thư pháp Trung Quốc", "Chữ cổ điển", "Nét cọ nghệ thuật, ý nghĩa văn hóa", "Trung Quốc", "Thấp", "Đơn giản", "Có", "SVG/PNG", "In lụa, DTG", "Xuất sắc", "Không", "Độ rõ ký tự, chính xác nét", "Thư pháp câu đối với triện đỏ", "P2", "Cần kiểm tra nhạy cảm văn hóa"),
        ("Nghệ thuật Ấn Độ", "Madhubani / Mithila", "Nghệ thuật dân gian mẫu phức tạp, màu tươi, họa tiết thiên nhiên", "Ấn Độ (Bihar)", "Cao", "Phức tạp", "Không", "JPG/PNG", "DTG, Thăng hoa", "Tốt", "Thấp", "Mật độ mẫu, bão hòa màu, đối xứng", "Tranh Madhubani công với viền hoa", "P1", "Mẫu dày đặc — test zoom chi tiết"),
        ("Nghệ thuật Ấn Độ", "Mandala", "Mẫu hình học tròn đối xứng, họa tiết tâm linh", "Ấn Độ/Tây Tạng", "Cao", "Cực cao", "Có", "SVG/PNG", "DTG, Thăng hoa", "Tốt", "Thấp", "Chính xác đối xứng tròn, nét mảnh ở rìa", "Mandala tinh xảo chi tiết vàng và ngọc lam", "P0", "Rất phổ biến POD — phải xử lý tốt chi tiết"),
        ("Nghệ thuật Ấn Độ", "Kalamkari", "Vẽ tay/in khuôn, chủ đề thần thoại, nhuộm tự nhiên", "Ấn Độ (AP/Telangana)", "Trung bình", "Phức tạp", "Không", "JPG/PNG", "DTG", "Tốt", "Thấp", "Dòng chảy mẫu hữu cơ, tái tạo tông đất", "Cây đời Kalamkari với chim và hoa", "P2", "Tông đất có thể khác nhau giữa các phương pháp in"),
        ("Nghệ thuật Châu Phi", "Bộ lạc / Mẫu hình học", "Hình hình học đậm, họa tiết biểu tượng, palette đất/tươi", "Châu Phi (nhiều vùng)", "Cao", "Vừa phải", "Không", "SVG/PNG", "In lụa, DTG, Thăng hoa", "Xuất sắc", "Không", "Căn chỉnh lặp mẫu, bảo toàn tương phản đậm", "Mẫu hình học bộ lạc Phi terracotta và đen", "P1", "Test ghép mẫu lặp liền mạch"),
        ("Nghệ thuật Châu Phi", "Kente / Ankara", "Mẫu dệt/in vải trên vải, ý nghĩa văn hóa", "Ghana / Tây Phi", "Rất cao", "Phức tạp", "Không", "JPG/PNG", "Thăng hoa", "Tốt", "Thấp", "Độ rực rỡ bảng màu truyền thống, căn sọc", "Mẫu vải Kente allover vàng và xanh lá", "P2", "Test in allover — cạnh tới cạnh"),
        ("Nghệ thuật Châu Phi", "Vải bùn (Bògòlanfini)", "Nhuộm bùn lên men, mẫu hình học đất", "Mali", "Thấp", "Đơn giản", "Không", "JPG/PNG", "In lụa, DTG", "Xuất sắc", "Không", "Chính xác tông đất, kết cấu hữu cơ", "Mẫu vải bùn nâu và kem", "P2", "Test cạnh mẫu không hoàn hảo hữu cơ"),
        ("Nghệ thuật Trung Đông", "Hình học Hồi giáo / Arabesque", "Tessellation hình học phức tạp, mẫu vô hạn", "Trung Đông / Thế giới Hồi giáo", "Trung bình", "Cực cao", "Không", "SVG/PNG", "Thăng hoa, DTG", "Xuất sắc", "Không", "Chính xác hình học, ghép liền mạch, chi tiết mảnh", "Mẫu ngôi sao hình học Hồi giáo xanh dương và vàng", "P1", "Hoàn hảo cho test in allover"),
        ("Nghệ thuật Mỹ Latinh", "Nghệ thuật dân gian Mexico / Alebrije", "Màu rực rỡ, sinh vật kỳ ảo, họa tiết Ngày Người Chết", "Mexico", "Rất cao", "Phức tạp", "Có", "PNG", "DTG", "Tốt", "Thấp", "Độ rực rỡ cực độ, render sinh vật chi tiết", "Rồng alebrije đầy màu sắc với mẫu phức tạp", "P1", "Kiểm tra gamut cho màu cực đoan"),
        ("Nghệ thuật Thổ dân", "Chấm Dot Painting", "Mẫu từ chấm, tông đất, câu chuyện thời mơ", "Úc", "Trung bình", "Vừa phải", "Không", "JPG/PNG", "DTG", "Tốt", "Thấp", "Rõ ràng mẫu chấm, kích thước chấm đều ở scale in", "Tranh chấm thổ dân kanguru dreamtime", "P2", "Chấm nhỏ có thể hòa vào ở độ phân giải thấp"),
        ("Nghệ thuật Hàn Quốc", "Tranh dân gian Minhwa", "Tranh dân gian tươi sáng, hổ, mẫu đơn, hình ảnh biểu tượng", "Hàn Quốc", "Cao", "Phức tạp", "Không", "JPG/PNG", "DTG", "Tốt", "Thấp", "Chính xác màu truyền thống, bảo toàn phong cách dân gian", "Tranh Minhwa hổ với chim và thông", "P2", "Thị trường đang quan tâm nhiều hơn"),
        ("Nghệ thuật Thái Lan", "Khon / Nghệ thuật đền", "Vàng lá, mẫu phức tạp, nhân vật thần thoại", "Thái Lan", "Rất cao", "Cực cao", "Không", "JPG/PNG", "DTG, Thăng hoa", "Tốt", "Trung bình", "Render màu vàng kim, chi tiết trang trí cực kỳ phức tạp", "Nghệ thuật đền Thái Garuda với đồ trang sức vàng", "P3", "Màu vàng kim thách thức cho in"),
        ("Nghệ thuật Châu Âu", "Phong cách Phục Hưng", "Tỷ lệ cổ điển, giải phẫu thực tế, tôn giáo/thần thoại", "Châu Âu (Ý)", "Cao", "Cực cao", "Không", "JPG/PNG", "DTG", "Tốt", "Cao", "Tái tạo mỹ thuật, tông da trên AI tryon", "Chân dung phong cách Phục Hưng theo lối Raphael", "P2", "AI Try-on phát hiện khuôn mặt vs mặt vẽ"),
        ("Nghệ thuật Celtic", "Nút thắt / Đan xen", "Mẫu đan lồng, không đầu cuối, xoắn ốc", "Ireland / Scotland", "Thấp", "Phức tạp", "Có", "SVG/PNG", "In lụa, DTG", "Xuất sắc", "Không", "Tính liên tục nút, nhất quán đường nét, co giãn", "Vòng tròn nút Celtic với nút trinity ở giữa", "P2", "Tốt cho test in lụa"),
    ],

    "👕 THIẾT KẾ POD / ÁO THUN": [
        ("Thiết kế Typography", "Slogan đậm", "Text lớn, động lực/hài hước, font ấn tượng", "Toàn cầu", "Thấp", "Đơn giản", "Có", "SVG/PNG", "In lụa, HTV, DTG", "Xuất sắc", "Không", "Render font, dễ đọc qua các kích cỡ", "Typography đậm 'JUST CREATE' font distressed", "P0", "Sản phẩm POD cốt lõi — phải hoàn hảo"),
        ("Thiết kế Typography", "Script Retro", "Chữ viết tay vintage, trang trí cầu kỳ", "Mỹ", "Trung bình", "Vừa phải", "Có", "SVG/PNG", "In lụa, DTG", "Tốt", "Không", "Dòng chảy chữ, bảo toàn nét mảnh", "Chữ viết tay retro 'California Vibes' với hoàng hôn", "P1", "Nét mảnh có thể biến mất ở kích thước nhỏ"),
        ("Áo đồ họa", "Huy hiệu Vintage / Emblem", "Badge tròn/khiên, kết cấu cũ, retro", "Mỹ", "Trung bình", "Vừa phải", "Có", "SVG/PNG", "In lụa, DTG", "Xuất sắc", "Không", "Đối xứng badge, rõ kết cấu distress", "Badge camping vintage với núi và đại bàng", "P0", "Thể loại POD bán chạy nhất — ưu tiên cao"),
        ("Áo đồ họa", "Streetwear / Đô thị", "Đồ họa đậm, ảnh hưởng graffiti, typography mạnh", "Toàn cầu (Đô thị)", "Cao", "Phức tạp", "Có", "PNG", "DTG, In lụa", "Tốt", "Thấp", "Chi tiết cạnh, kết cấu graffiti", "Thiết kế streetwear đầu lâu với splash graffiti neon", "P1", "Phổ biến cho thị trường trẻ"),
        ("Nghệ thuật động vật", "Chân dung động vật thực tế", "Hình ảnh động vật giống thật, tập trung hoang dã", "Toàn cầu", "Cao", "Cực cao", "Có", "PNG", "DTG", "Tốt", "Thấp", "Chi tiết lông/lông vũ, render mắt, trong suốt nền", "Chân dung sói thực tế đôi mắt xanh dữ dội", "P1", "Niche POD luôn phổ biến"),
        ("Nghệ thuật động vật", "Động vật hình học / Đa giác", "Động vật xây từ hình hình học, phong cách hiện đại", "Toàn cầu", "Trung bình", "Vừa phải", "Có", "SVG/PNG", "DTG, In lụa", "Xuất sắc", "Không", "Chính xác hình dạng, gradient fill trong đa giác", "Đầu gấu low-poly hình học tone ngọc bích", "P1", "Cạnh hình học sạch là quan trọng"),
        ("Thiên nhiên / Phong cảnh", "In phong cảnh", "Cảnh núi, biển, rừng cho in áo", "Toàn cầu", "Cao", "Phức tạp", "Không", "JPG/PNG", "DTG, Thăng hoa", "Tốt", "Thấp", "Chính xác màu tự nhiên, vị trí đường chân trời", "Phong cảnh núi giờ vàng với hồ phản chiếu", "P2", "Định dạng in full-front hoặc allover"),
        ("Mẫu lặp / Allover", "Mẫu hoa", "Mẫu hoa/thực vật lặp, ghép liền mạch", "Toàn cầu", "Cao", "Phức tạp", "Không", "JPG/PNG", "Thăng hoa", "Xuất sắc", "Thấp", "Chính xác lặp liền mạch, nhất quán màu qua tile", "Mẫu hoa nhiệt đới liền mạch với hoa dâm bụt", "P1", "In thăng hoa allover — test căn đường may"),
        ("Mẫu lặp / Allover", "Mẫu hình học lặp", "Hình hình học lặp, tessellation", "Toàn cầu", "Trung bình", "Vừa phải", "Không", "SVG/PNG", "Thăng hoa", "Xuất sắc", "Không", "Căn chỉnh tile, tỷ lệ mẫu qua các size", "Mẫu hình học art deco liền mạch vàng và navy", "P1", "Test cùng mẫu từ S đến 3XL"),
        ("Mẫu lặp / Allover", "Rằn ri / Quân sự", "Mẫu ngụy trang nhiều bảng màu", "Toàn cầu", "Trung bình", "Vừa phải", "Không", "JPG/PNG", "Thăng hoa", "Xuất sắc", "Thấp", "Hòa trộn hình hữu cơ, chính xác bảng màu", "Mẫu rằn ri đô thị tông xám", "P2", "Test vỡ mẫu ở đường may"),
        ("Tối giản", "Icon / Biểu tượng đơn", "Thiết kế rất đơn giản một phần tử, nét sạch", "Toàn cầu", "Thấp", "Đơn giản", "Có", "SVG/PNG", "In lụa, HTV", "Xuất sắc", "Không", "Rõ icon ở vị trí nhỏ, cạnh sắc nét", "Icon trái tim nét đơn tối giản giữa ngực", "P0", "Thiết kế đơn giản nhất — test hiệu năng nền tảng"),
        ("Văn hóa đại chúng", "Parody / Mashup", "Tham chiếu văn hóa pop, mashup, hài hước", "Toàn cầu", "Cao", "Phức tạp", "Có", "PNG", "DTG", "Tốt", "Thấp", "Chi tiết nhân vật, chính xác màu cho parody", "Mashup văn hóa pop mèo vũ trụ với pizza", "P2", "Cần lưu ý bản quyền/IP"),
        ("Thể thao / Đội nhóm", "Số áo Jersey", "Đánh số thể thao, đồ họa kiểu đội", "Toàn cầu", "Thấp", "Đơn giản", "Có", "SVG/PNG", "In lụa, HTV", "Xuất sắc", "Không", "Căn số, nhất quán vị trí trước/sau", "Số áo thể thao 23 với tên đội", "P2", "Test đăng ký in hai mặt"),
    ],

    "⚠️ CÁC TRƯỜNG HỢP THÁCH THỨC KỸ THUẬT": [
        ("Edge Case", "Toàn cảnh siêu rộng", "Artwork tỷ lệ rất rộng (3:1 hoặc hơn)", "N/A", "Cao", "Phức tạp", "Không", "JPG/PNG", "DTG", "Thách thức", "Trung bình", "Cắt tỷ lệ, hành vi auto-fit", "Dãy núi toàn cảnh tỷ lệ 3:1", "P0", "Test logic auto-crop / fit của platform"),
        ("Edge Case", "Dọc siêu cao", "Artwork tỷ lệ rất cao (1:3 hoặc hơn)", "N/A", "Trung bình", "Vừa phải", "Không", "JPG/PNG", "DTG", "Thách thức", "Thấp", "Auto-fit dọc, căn chỉnh vùng áo", "Tranh cuộn dọc Nhật Bản cao", "P1", "Test xử lý căn chỉnh dọc"),
        ("Edge Case", "Chi tiết siêu nhỏ", "Đường cực mảnh và chi tiết rất nhỏ", "N/A", "Thấp", "Cực cao", "Có", "SVG/PNG", "DTG", "Thách thức", "Không", "Hiển thị đường ở kích thước in, độ rộng đường tối thiểu", "Mandala cực chi tiết với đường 0.5pt", "P0", "Test ngưỡng chi tiết in được tối thiểu"),
        ("Edge Case", "Màu neon / Ngoài gamut", "Màu ngoài gamut CMYK, neon điện", "N/A", "Rất cao", "Vừa phải", "Không", "PNG", "DTG", "Thách thức", "Thấp", "Cắt gamut màu, fallback render neon", "Nghệ thuật trừu tượng xanh neon và xanh điện", "P0", "QUAN TRỌNG: Test gamut mapping cho chính xác in"),
        ("Edge Case", "Artwork đen trên áo tối", "Artwork chỉ đen đặt trên áo đen", "N/A", "Thấp", "Đơn giản", "Có", "PNG", "DTG (lớp trắng nền)", "Thách thức", "Không", "Kiểm tra hiển thị, kích hoạt lớp trắng nền", "Nghệ thuật tattoo đen trên áo đen", "P1", "Platform nên cảnh báo hoặc tự điều chỉnh"),
        ("Edge Case", "Artwork toàn trắng", "Thiết kế chỉ trắng, cần ngữ cảnh áo màu", "N/A", "Thấp", "Đơn giản", "Có", "PNG", "DTG (mực trắng), HTV", "Thách thức", "Không", "Xử lý mực trắng, phân biệt trong suốt vs trắng", "Logo silhouette trắng trên nền trong suốt", "P0", "Test logic phát hiện màu trắng"),
        ("Edge Case", "Độ phân giải rất thấp (72 DPI)", "Ảnh gốc độ phân giải web, không đủ cho in", "N/A", "Trung bình", "Đơn giản", "Không", "JPG", "DTG", "Thách thức", "Thấp", "Hệ thống cảnh báo DPI, kiểm tra chất lượng upscale", "Artwork JPG 500x500px độ phân giải thấp", "P0", "Platform phải cảnh báo chất lượng kém"),
        ("Edge Case", "Siêu cao phân giải (600+ DPI)", "File cực lớn, sử dụng bộ nhớ cao", "N/A", "Cao", "Cực cao", "Không", "PNG/TIFF", "DTG", "Xuất sắc", "Thấp", "Hiệu năng upload, xử lý bộ nhớ, thời gian xử lý", "Artwork 8000x8000px ở 600 DPI", "P0", "Test hiệu năng / timeout / crash"),
        ("Edge Case", "GIF động → Tĩnh", "User upload GIF động, platform phải xử lý", "N/A", "Trung bình", "Đơn giản", "Có", "GIF", "DTG", "Thách thức", "Không", "Trích xuất frame đầu, xử lý từ chối animation", "GIF lấp lánh động upload làm artwork", "P1", "Test xử lý lỗi hoặc chọn frame"),
        ("Edge Case", "Upload PDF CMYK", "PDF sẵn sàng in trong không gian màu CMYK", "N/A", "Trung bình", "Vừa phải", "Không", "PDF", "DTG", "Tốt", "Không", "Chuyển đổi CMYK sang RGB, kiểm tra lệch màu", "PDF CMYK logo thương hiệu", "P1", "Test hỗ trợ đa định dạng file"),
        ("Edge Case", "Text cực lớn", "Text lớn che toàn bộ mặt trước áo", "N/A", "Thấp", "Đơn giản", "Có", "SVG/PNG", "In lụa, DTG", "Tốt", "Không", "Giới hạn scale text, tràn ranh giới áo", "Một chữ 'A' phủ toàn bộ vùng in", "P1", "Test ranh giới scale tối đa"),
        ("Edge Case", "Nhiều vật thể nhỏ", "100+ icon/vật thể nhỏ trong một artwork", "N/A", "Cao", "Cực cao", "Có", "PNG/SVG", "DTG", "Thách thức", "Thấp", "Rõ ràng vật nhỏ, hiệu năng render", "Mẫu 100 emoji icon nhỏ khác nhau", "P2", "Test stress render"),
        ("Edge Case", "Ảnh có khuôn mặt người", "Ảnh thật với khuôn mặt người rõ ràng", "N/A", "Cao", "Cực cao", "Không", "JPG", "DTG", "Tốt", "Cao", "AI Try-on nhầm mặt in với mặt model", "Ảnh chân dung chất lượng cao trên áo", "P0", "QUAN TRỌNG: AI try-on phải phân biệt mặt in vs mặt model"),
        ("Edge Case", "Cạnh gradient trong suốt", "Cạnh artwork mờ dần thành trong suốt", "N/A", "Trung bình", "Vừa phải", "Có", "PNG", "DTG", "Tốt", "Trung bình", "Render gradient trong suốt trên vải", "Hiệu ứng khói mờ từ đặc sang trong suốt", "P1", "Test xử lý alpha gradient trên áo"),
    ],
}
